version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Generate code coverage
          command: node_modules/nyc report --reporter=text-lcov
      - store_artifacts:
          path: test-results.xml
      - store_artifacts:
          path: coverage
          
